blank_issues_enabled: false
contact_links: 
  - name: Discord Server
    about: 'Q & A'
    url: 'https://discord.gg/pbyWbUYjyt'
  - name: 'Documentation'
    about: 'Generated Documentation'
    url: 'https://valapi.github.io/docs'
  - name: 'Guide'
    about: 'Basic usage'

    url: 'https://valapi.github.io/guide'
